
GET http://localhost:3000/tasks
###

GET http://localhost:3000/tasks/2
###

POST http://localhost:3000/tasks
content-type: application/json

{
  "name": "Buy milk",
  "description": "eslkajskdfjl"
}
###

PUT  http://localhost:3000/tasks/1
content-type: application/json

{
  "name": "mod_name",
  "description": "ddd"
}
###

DELETE  http://localhost:3000/tasks/1
content-type: application/json
###